export const state = {
  bpm: 120,
  isPlaying: false,
  isRecording: false,
  currentTrack: 0,
  playheadBeat: 0,

  tracks: [
    {
      id: 0,
      name: "Lead",
      color: "#ff6b9d",
      type: "synth",
      preset: "pluck",
      muted: false,
      notes: [],
    },
    {
      id: 1,
      name: "Bass",
      color: "#4ecdc4",
      type: "synth",
      preset: "subBass",
      muted: false,
      notes: [],
    },
    {
      id: 2,
      name: "Drums",
      color: "#ffe66d",
      type: "synth",
      preset: "noise",
      muted: false,
      notes: [],
    },
    {
      id: 3,
      name: "FX",
      color: "#a78bfa",
      type: "synth",
      preset: "pad",
      muted: false,
      notes: [],
    },
  ],

  keymap: {
    a: "C4",
    w: "C#4",
    s: "D4",
    e: "D#4",
    d: "E4",
    f: "F4",
    t: "F#4",
    g: "G4",
    y: "G#4",
    h: "A4",
    u: "A#4",
    j: "B4",
    k: "C5",
    z: "C3",
    x: "D3",
    c: "E3",
    v: "F3",
    b: "G3",
    n: "A3",
    m: "B3",
  },
};
